/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import { JSXElements } from '@stencil/core';

import '@stencil/router'
import '@stencil/state-tunnel'



interface AppHome {}
interface AppHomeAttributes extends JSXElements.HTMLAttributes {}

interface TyburnApp {}
interface TyburnAppAttributes extends JSXElements.HTMLAttributes {}

export interface LocalElementInterfaces  {
  'AppHome': AppHome;
  'TyburnApp': TyburnApp;
}

export interface LocalIntrinsicElements {
  'app-home': AppHomeAttributes;
  'tyburn-app': TyburnAppAttributes;
}

declare global {

  interface HTMLAppHomeElement extends AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLTyburnAppElement extends TyburnApp, HTMLStencilElement {}
  var HTMLTyburnAppElement: {
    prototype: HTMLTyburnAppElement;
    new (): HTMLTyburnAppElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'tyburn-app': HTMLTyburnAppElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'tyburn-app': HTMLTyburnAppElement;
  }
}


import { DefaultIntrinsicElements } from '@stencil/core';

declare global {
  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends LocalIntrinsicElements, DefaultIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends JSXElements.HTMLAttributes {}
}

